### PR TITLE
YOU WANT AUTO COMPLETE? HAVE SOME AUTO COMPLETE

### PR DESCRIPTION
**Pull request by hyperwidget**
## Screenshot

autocomplete

## What Changed & Why

Added some autocomplete and some instructions on how to set it up - unfortunately it's not _super_ stable or _super_ fast. But! It mostly works and should be enough to get running

## In Progress/Follow Up

We should generate the list of components
We should _also_ maybe look to see if there are npm install post install hooks to auto set this stuff up for people

### CODE REVIEW

**Comment by hyperwidget** [comment]
@nicolechung that's a very good question. The short answer is that I'm not sure.

The slightly _less_ shorter version is that you're _supposed_ to be able to do it by adding your dev version of trt.js to your path and then adjusting the command to populate the completion values using that (something like: `devtrt completion bash > $(brew --prefix)/etc/bash_completion.d/trt`) and in theory that _should_ do it.

If I'm being honest, trying to get that going sounded like too much effort for the value, so I didn't spend the time to figure it out

**Comment by nicolechung** [comment]
Let's just merge this then!

**Comment by nicolechung** [comment]
Actually, @hyperwidget wait, what about that package error?

Can you try an `npm install` and see if there is some dependency problem with `w3c-hr-time`?

**Comment by hyperwidget** [comment]
I do not get any issues - I'd be keen to see if anyone else has any issues if they have time to give it a good ol' college try.

@spiderbites, @ruhee ?

**Comment by spiderbites** [comment]
I don't get any errors running `npm install`, however it changes my lockfile...

I'm using the `zsh` shell which comes with autocomplete out of the box.  I can't quite get it all working but perhaps this would be nice to make it a bit more shell agnostic: 
```
trt.js completion `echo $SHELL | xargs basename`
```

**Pull request merged**
